# https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/basheer421/iot-bammar.git
    targetRevision: master
    path: p3/confs/conf.yml # Target (Only redeploy on this path change)
  destination:
    server: https://kubernetes.default.svc # "default for namespace, svc for service"
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true # Looks for target changes only

